name: CI - runbook-executor

on:
  push:
    branches: [ main ]
    paths:
      - 'runbook-executor/**'
      - '.github/workflows/ci-python.yml'
  pull_request:
    paths:
      - 'runbook-executor/**'
      - '.github/workflows/ci-python.yml'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runbook-executor
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            runbook-executor/requirements.txt
            runbook-executor/requirements-dev.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Ruff
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Mypy
        run: mypy .
      - name: Pytest with coverage
        run: pytest --cov=. --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: runbook-executor/coverage.xml

  publish:
    if: startsWith(github.ref, 'refs/tags/runbook-executor-v')
    needs: build-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runbook-executor
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: runbook-executor/dist/
          skip-existing: true