name: CI - Python

on:
  push:
  pull_request:

jobs:
  runbook-executor-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runbook-executor
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest -q