# Sample configuration for ticket-bridge
# Optional: token required in header X-Bridge-Token for /webhook requests
# bridge_token: "change-me"
secret_token: "replace-me"
runbook_executor_url: "http://localhost:5001/run"
timeouts:
  request_seconds: 10
  connect_seconds: 5